### ISSUE TITLE
unable to build OscMackieControl

### ISSUE THREAD

**Issue by scientificsound** [NicoG60/OscMackieControl#3]
Hi, 

I'm trying to build OscMackieControl and I've run into a problem that I can't seem to google my way out of...

Initially, I was having trouble because the thirdPArty/osc-cpp-qt and /rtmidi folders were empty; when I tried to run ```make -j 4``` I was getting errors like:
```./MidiIO.h:16:10: fatal error: 'RtMidi.h' file not found```
and
```./OscIO.h:18:10: fatal error: 'osc/composer/OscMessageComposer.h' file not found```

After manually cloning the two packages and following the instructions to build rtmidi and using ```qmake OSC.pro``` and ```make``` to build the osc-cpp-qt ```/bin``` directory, that issue seems to be resolved.  

However, now when I run ```make -j 4```, after a bunch of normal(?) looking output, I get the following error:
```ld: library not found for -lrtmidi```
```clang: error: linker command failed with exit code 1 (use -v to see invocation) make: *** [../build/release/OscMackieControl.app/Contents/MacOS/OscMackieControl] Error 1```

And indeed, I can't find a ```lrtmidi``` file anywhere in the rtmidi directory.  I'm sure this is a bit of a noob issue, but any help solving it would be greatly appreciated.

Thanks!
-eric

**Comment by NicoG60** [comment]
Hi Eric!

you can have a look at the [Release page](https://github.com/NicoG60/OscMackieControl/releases/tag/v1.0), there is pre-build binaries for macOS and Windows.

If you want to build it anyway:

This is because rtmidi and osc-cpp-qt are git submodules. This is a lack of documentation from me sorry.
If you messed with those directory, I would recommend to delete everything and to start again from a freshly cloned repository

Before you try to build the application, you need to run the following:
```bash
git submodule init
git submodule update
```

then go in each directory and build the corresponding dependancies.
in the osc-cpp-qt directory:
```
qmake OSC.pro
make
```

in the rtmidi directory:
```
cmake .
make
```

If all those steps are successful, you can try to build the application.

**Comment by scientificsound** [comment]
Thanks for the quick reply!

Since I came so far already, I wanted to try and build it myself.  Everything seems to have worked (except it printed ```ERROR: Unexpected prefix "@loader_path"``` 21 times in the terminal before finishing), but regardless, the app is working, I'm able to communicate w/ my DAW!

Thanks so much for your help and for providing this!

cheers,
-eric

**Comment by NicoG60** [comment]
Hey! Happy to read that!
about the error message, never saw it before, weird...
Give me a shout if there is any issue.

**Comment by scientificsound** [comment]
thanks! will do...
