### ISSUE TITLE
Macos UDP strangeness

### ISSUE THREAD

**Issue by shayneoneill** [NicoG60/OscMackieControl#8]
hey, so I've been using this as the bridge for another project of mine that uses your OSC mapping to interface with my DAW. Working great so far however I've noticed a couple of head-scratchers.

When working 127.0.0.1 locally, everything works great ( a few crashes on the v2 line but to be expected for a work in progress). However when I try and move my project onto a rapsberry pi I havent been able to establish communication. 

This MIGHT be something external to what your doing, but when I run wireshark I dont see incoming UDP nor do I see outgoing. 

I've disabled the firewall completely but no joy. Has this been fully tested on a mac outside of 127.0.0.1? 

Regards,
Shayne.

**Comment by NicoG60** [comment]
Hi Shayne

Correct me if I'm wrong but what you try to do is:
- raspi as a controller
- macbook with DAW + OscMackieControl

If that's the case then it should work as expected. It is tested and work on LAN network with a remote controller. I'm a mac guy and I'm coding and testing primarily on mac. I'm also testing using an iPad as a controller is it's the same kinda configuration as yours.
I've not upgrade to Big Sur yet so not tested on that.
I've not tested on a routed setup and only made it work on a LAN / within the same subnet.

---

On the other end if your config is:
- raspi with DAW + OscMackieControl
- macbook as controller

The software as not been tested on linux at all, I've simply not took the time to install a linux box and try it as I'm mainly using win and macos and that most of musician and DAW owner will probably be the same.

What's you're project? What are you trying to do? 

Regards
Nicolas

**Comment by shayneoneill** [comment]
Yeah I worked it out in the end, wasn't on your side. Though it was the other way around. Macbook running daw and some custom code on the raspberry pi (C++ software using QT stack and the osc library that I believe your first version was using. Turns out the UDP ports work a bit differently than I expected. 

You can close this issue.  

One final thing though, is the /Timecode OSC stuff implemented yet. I havent seen that emitted yet (from Studio one). When I plug it into my old Mackie MCU the midi seems geenrated fine so I wonder if this is on the "TODO" (Using V2 of your software)

**Comment by NicoG60** [comment]
Part of it is done and looks like it works using cubase but I probably missed something. I'm currently reviewing that part of the software as the opened pull request is related to how interpreting data sent from the saw for assignment and timewise display. This has presumably something to do with your issue.I just don't find the time to do it these days... On 25 Feb 2021 05:34, shayneoneill <notifications@github.com> wrote:
Yeah I worked it out in the end, wasn't on your side. Though it was the other way around. Macbook running daw and some custom code on the raspberry pi (C++ software using QT stack and the osc library that I believe your first version was using. Turns out the UDP ports work a bit differently than I expected.
You can close this issue.
One final thing though, is the /Timecode OSC stuff implemented yet. I havent seen that emitted yet (from Studio one). When I plug it into my old Mackie MCU the midi seems geenrated fine so I wonder if this is on the "TODO" (Using V2 of your software)
